language: node_js

node_js:
  - 16
  
install:
    - npm install

branches:
  only:
  - main

deploy:
  - provider: heroku
    api_key: 22c5b519-a454-4299-8cab-4cdb244b1283
    app: dev-moviescombine
    on:
      branch: main
